### ISSUE TITLE
Transfer `lckr/jupyterlab-variableInspector` to `jupyterlab-contrib`

### ISSUE THREAD

**Issue by lckr** [jupyterlab-contrib/jupyterlab-contrib.github.io#59]
# Target
Variable inspector extension for JupyterLab. Currently supports table view of active variables and a data grid viewer for matrix like objects for python kernels (some minor support for R and scala is also available).

- The code repository: https://github.com/lckr/jupyterlab-variableInspector
- The npm package on npmjs.com (if available): [@lckr/jupyterlab_variableinspector](https://www.npmjs.com/package/@lckr/jupyterlab_variableinspector)
- The python package on pypi.org (if available): https://pypi.org/project/lckr-jupyterlab-variableinspector/
- The conda-forge recipe on https://github.com/conda-forge (if available): https://github.com/conda-forge/jupyterlab-variableinspector-feedstock

# Reason

I'm happy to see that there is some interest in keeping this extension alive. Since I couldn't find the time to keep it updated in the past (and will not be able to do so in the near future) but would love to see it getting supported in the future as well I want to transfer the project to the jupyterlab-contrib org.

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyterlab-contrib` organization (check one of):
  - [ ] Help with all `jupyterlab-contrib` repositories
  - [ ] Help with the transferred repository only
  - [x] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [ ] Must keep the extension name
  - [ ] Cannot use the original name
  - [x] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The extension is working on at least JupyterLab 2.x
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [ ] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online 
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

**Comment by fcollonval** [comment]
Thanks @lckr 

in order to transfer the extension to this organization, you will need to carry out action on three web services:
- GitHub:
  - [ ] Accept invitation as owner to jupyterlab-contrib organization
  - [ ] [Enable 2FA](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication)
  - [ ] [Transfer the repository to this organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)
- PyPI:
  - [ ] Accept the invitation to the jupyterlab-contrib PyPI organization
  - [ ] [Enable 2FA](https://pypi.org/help/#totp)
  - [ ] Add the package to the organization: https://pypi.org/manage/organization/jupyterlab-contrib/projects/#add-project-to-organization
- NPM:
  - [ ] Accept the invitation to the jlab-contrib NPM organization
  - [ ] [Enable 2FA](https://docs.npmjs.com/configuring-two-factor-authentication)
  - [ ] Ping us here so we can grant you with the proper right to add the package in the organization
  - [ ] Add the package to the _developers_ team: https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access
- conda-forge:
   - Nothing to do I saw I'm already maintainer of the recipe :smile: 

> Note: for transferring the package, you may be granted extensive rights that will be reduced later one to hacker attack surface.

Don't hesitate to ping me here if you have questions or troubles with the above steps.

**Comment by lckr** [comment]
> Thanks @lckr
> 
> in order to transfer the extension to this organization, you will need to carry out action on three web services:
> 
>     * GitHub:
>       
>       * [x]  Accept invitation as owner to jupyterlab-contrib organization
>       * [x]  [Enable 2FA](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication)
>       * [x]  [Transfer the repository to this organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)
> 
>     * PyPI:
>       
>       * [x]  Accept the invitation to the jupyterlab-contrib PyPI organization
>       * [x]  [Enable 2FA](https://pypi.org/help/#totp)
>       * [x]  Add the package to the organization: https://pypi.org/manage/organization/jupyterlab-contrib/projects/#add-project-to-organization
> 
>     * NPM:
>       
>       * [x]  Accept the invitation to the jlab-contrib NPM organization
>       * [x]  [Enable 2FA](https://docs.npmjs.com/configuring-two-factor-authentication)
>       * [ ]  Ping us here so we can grant you with the proper right to add the package in the organization
>       * [ ]  Add the package to the _developers_ team: https://www.npmjs.com/settings/jlab-contrib/teams/team/developers/access

Hi @fcollonval, I transferred the repo and the pypi package and now require the proper rights for npm as well :)

**Comment by fcollonval** [comment]
Thanks a lot for the quick follow-up @lckr 

I increased your right on NPM. So you should be able to do the transfer now. Let me know if have any errors/questions.

**Comment by lckr** [comment]
Thanks, that worked well. I added the package to the `developer` team and removed my own user as a maintainer from the package as well. Now that everything has been transfered you can go ahead and restrict my access rights again :)

Somethings I probably would change:
- rename pypi package [lckr-jupyterlab-variableinspector/](https://pypi.org/project/lckr-jupyterlab-variableinspector/) to something more general, e.g., `jupyterlab-variable-inspector`
- Same for the npm package @lckr/jupyterlab_variableinspector

**Comment by fcollonval** [comment]
Although the naming is not always optimal, we prefer to keep the existing name to ease the upgrade by the users. But if you want us to not do so. We'll do the renaming.
